# Generated by Django 2.0 on 2018-07-19 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Btitle', models.CharField(default='blog title', max_length=32)),
                ('Bcontent', models.TextField(null=True)),
                ('Bpublish_time', models.DateTimeField(null=True)),
                ('Bauthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Bpublish_time',),
            },
        ),
    ]
