# Generated by Django 2.0 on 2018-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_barticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ctitle', models.CharField(default='blog title', max_length=32)),
                ('Ccontent', models.TextField(null=True)),
                ('Cpublish_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
